[workspace]
resolver = "2"
members = [
    "tracepoint",
    "tracepoint_decode",
    "eventheader",
    "eventheader_dynamic",
    "eventheader_macros",
    "eventheader_types",
    "tracepoint_perf",
]
